# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-07-28 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotatedrecording',
            name='version_num',
        ),
        migrations.AddField(
            model_name='annotatedrecording',
            name='hash_string',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annotatedrecording',
            name='ayah_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annotatedrecording',
            name='surah_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
