# Generated by Django 2.0.1 on 2018-07-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20180728_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotatedrecording',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
