# Generated by Django 2.0.1 on 2018-08-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20180729_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotatedrecording',
            name='session_id',
            field=models.CharField(default=-1, max_length=32),
            preserve_default=False,
        ),
    ]
