# Generated by Django 2.0.1 on 2018-08-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20180729_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemographicInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=32)),
                ('platform', models.CharField(default='web', max_length=32)),
                ('gender', models.CharField(max_length=32)),
                ('age', models.CharField(max_length=32)),
                ('ethnicity', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
