# Generated by Django 2.0.1 on 2018-08-05 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_annotatedrecording_session_id'),
        ('restapi', '0004_demographicinformation'),
    ]

    operations = [
    ]
