# Generated by Django 2.0.1 on 2018-08-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_merge_20180805_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographicinformation',
            name='country',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='demographicinformation',
            name='ethnicity',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
