# Generated by Django 2.0.1 on 2018-08-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_auto_20180805_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographicinformation',
            name='session_id',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
