# Generated by Django 2.0.1 on 2018-08-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_auto_20180805_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographicinformation',
            name='country',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='demographicinformation',
            name='ethnicity',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
