# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-01 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_auto_20180805_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographicinformation',
            name='qiraah',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
